### ISSUE TITLE
1.21.4: GSON serializer crash: There is no data holder converter registered to convert from BinaryTagHolderImpl to GsonDataComponentValue

### ISSUE THREAD

**Issue by kangarko** [KyoriPowered/adventure#1144] opened 2024-12-16 17:50 UTC
Sorry for opening so many issues, we're testing a chat plugin utilizing every aspect of Adventure so we're trying to push it to the edge.

On 1.21.4, GSON component serializer crashes when the message contains enchantments.

**Server version**: This server is running Paper version 1.21.4-14-master@b746d9d (2024-12-11T21:22:39Z) (Implementing API version 1.21.4-R0.1-SNAPSHOT)

**Mini version of this message:**

```
X was slained by kangarko holding <hover:show_item:netherite_sword:1:enchantments:'{levels:{"minecraft:sharpness":100}}'>Netherite Sword (<hover:show_text:'Hey this is a test'>[</yellow>d</>e</>a</>t</>h</> </>m</>e</>s</>s</>a</>g</gray>e</>,</> </>h</>o</>v</>e</>r</> </>m</>e</>]</blue></hover>)</hover>
```

**Error log upon calling GsonComponentSerializer.gson().serialize():**

```
[18:23:43 INFO]: java.lang.IllegalArgumentException: There is no data holder converter registered to convert from a class net.kyori.adventure.nbt.api.BinaryTagHolderImpl instance to a interface net.kyori.adventure.text.serializer.gson.GsonDataComponentValue (on field minecraft:enchantments)
[18:23:43 INFO]: 	at net.kyori.adventure.text.event.DataComponentValueConverterRegistry.convert(DataComponentValueConverterRegistry.java:90)
[18:23:43 INFO]: 	at net.kyori.adventure.text.event.HoverEvent$ShowItem.dataComponentsAs(HoverEvent.java:623)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.ShowItemSerializer.write(ShowItemSerializer.java:139)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.ShowItemSerializer.write(ShowItemSerializer.java:49)
[18:23:43 INFO]: 	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:298)
[18:23:43 INFO]: 	at com.google.gson.Gson.toJson(Gson.java:944)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.StyleSerializer.write(StyleSerializer.java:296)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.StyleSerializer.write(StyleSerializer.java:62)
[18:23:43 INFO]: 	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:298)
[18:23:43 INFO]: 	at com.google.gson.Gson.toJson(Gson.java:944)
[18:23:43 INFO]: 	at com.google.gson.Gson.toJsonTree(Gson.java:802)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:252)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:77)
[18:23:43 INFO]: 	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:298)
[18:23:43 INFO]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:73)
[18:23:43 INFO]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:99)
[18:23:43 INFO]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:59)
[18:23:43 INFO]: 	at com.google.gson.Gson.toJson(Gson.java:944)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:263)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:77)
[18:23:43 INFO]: 	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:298)
[18:23:43 INFO]: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:73)
[18:23:43 INFO]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:99)
[18:23:43 INFO]: 	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(CollectionTypeAdapterFactory.java:59)
[18:23:43 INFO]: 	at com.google.gson.Gson.toJson(Gson.java:944)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:263)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.write(ComponentSerializerImpl.java:77)
[18:23:43 INFO]: 	at com.google.gson.TypeAdapter$1.write(TypeAdapter.java:298)
[18:23:43 INFO]: 	at com.google.gson.Gson.toJson(Gson.java:944)
[18:23:43 INFO]: 	at com.google.gson.Gson.toJson(Gson.java:899)
[18:23:43 INFO]: 	at com.google.gson.Gson.toJson(Gson.java:848)
[18:23:43 INFO]: 	at com.google.gson.Gson.toJson(Gson.java:825)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.serialize(GsonComponentSerializerImpl.java:104)
[18:23:43 INFO]: 	at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.serialize(GsonComponentSerializerImpl.java:41)
[18:23:43 INFO]: 	at ChatControl.jar//org.mineacademy.fo.model.SimpleComponent.toAdventureJson(SimpleComponent.java:779)
[18:23:43 INFO]: 	at ChatControl.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.executeOperators(PlayerMessage.java:1214)
[18:23:43 INFO]: 	at ChatControl.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:797)
[18:23:43 INFO]: 	at ChatControl.jar//org.mineacademy.chatcontrol.operator.PlayerMessage$PlayerMessageCheck.filter(PlayerMessage.java:1)
[18:23:43 INFO]: 	at ChatControl.jar//org.mineacademy.chatcontrol.operator.Operator$OperatorCheck.start(Operator.java:793)
[18:23:43 INFO]: 	at ChatControl.jar//org.mineacademy.chatcontrol.operator.PlayerMessages.broadcast(PlayerMessages.java:191)
[18:23:43 INFO]: 	at ChatControl.jar//org.mineacademy.chatcontrol.listener.PlayerListener.onDeath(PlayerListener.java:318)
[18:23:43 INFO]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor93.execute(Unknown Source)
[18:23:43 INFO]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[18:23:43 INFO]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[18:23:43 INFO]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
```

Please let me know if I am doing something wrong or this is a problem in Adventure itself.

**Comment by zml2008** [comment] 2024-12-22 02:03
Duplicate of #1130

**Closed as duplicate by zml2008** 2024-12-22 02:03 UTC
Labels: resolution: duplicate

**Comment by kangarko** [comment] 2024-12-23 13:55
Thanks for noticing!
