### ISSUE TITLE
Text replacement doesn't support hover events

### ISSUE THREAD

**Issue by TheSirCororo** [KyoriPowered/adventure#435] opened 2021-08-31 16:30 UTC
I want to replace some text to component that open url and on hover show text
this is my code: (kotlin)
```kt
newMessage = newMessage.replaceText {
            it.match(config.blockLinkRegex).replacement(
                Component.text("Test msg").clickEvent (ClickEvent.openUrl("https://google.ru/"))
                    .hoverEvent(
                        HoverEvent.showText(
                            Component.text("cool")
                        )
                    )
            )
}
```
When I send this message, it not clickable or hoverable, after replace only content and style are saved

**Comment by kezz** [comment] 2021-08-31 16:54
Click event replacing is a duplicate of #236.

**Comment by zml2008** [comment] 2023-01-13 03:00
This issue doesn't have enough information to reproduce -- and it does appear that text replacement should handle hover events as it stands. Feel free to provide a standalone reproducer (not depending on other parts of the plugin or unknown inputs) if this issue still applies.

**Closed by zml2008** 2023-01-13 03:00 UTC
Labels: type: enhancement, area: api
