### ISSUE TITLE
Strikethrough on a string with only spaces does not get colored

### ISSUE THREAD

**Issue by partydev** [KyoriPowered/adventure#809] opened 2022-08-13 21:19 UTC
Strikethrough with only spaces:
![image](https://user-images.githubusercontent.com/42015460/184511004-44cdde19-c68a-44b8-a9a3-6f644409efea.png)

Strikethrough with a letter prefix:
![image](https://user-images.githubusercontent.com/42015460/184511013-82e44d1f-8f47-4c99-b12a-8a35928cc6a5.png)

Currently impossible to make horizontal bars colored currently unless a non-space character is in the string.

**Comment by kezz** [comment] 2022-08-13 22:45
Wrong repo. Also a duplicate of https://github.com/KyoriPowered/adventure-webui/issues/117.

**Closed** 2022-08-13 22:45 UTC
