### ISSUE TITLE
Tag writer is outdated for packets

### ISSUE THREAD

**Issue by Snowbelldog** [KyoriPowered/adventure#988] opened 2023-10-18 14:34 UTC
After some trial and error and constant kicks I have now found out that there is an update in NBT which have not yet been updated in adventure. Well I've been sitting on it for some time now because I almost didn't think it was possible.

Here is the link to the protocol wiki: https://wiki.vg/NBT#Network_NBT_(Java_Edition)
in net.kyori.adventure.nbt.BinaryTagWriterImpl
```java
public void write(final @NotNull CompoundBinaryTag tag, final @NotNull DataOutput output) throws IOException {
     output.writeByte(BinaryTagTypes.COMPOUND.id());
     output.writeUTF("");
     BinaryTagTypes.COMPOUND.write(tag, output);
}
```
new or a second method
```java
public void write(final @NotNull CompoundBinaryTag tag, final @NotNull DataOutput output, ?VersionIdentifier?) throws IOException {
    output.writeByte(BinaryTagTypes.COMPOUND.id());
    if(?VersionIdentifier? < 1_20_2)
        writeShort(0); //or output.writeUTF(""); for more calculation steps
    BinaryTagTypes.COMPOUND.write(tag, output);
}
```

**Comment by zml2008** [comment] 2023-10-18 14:37
Duplicate of #968

**Closed as not planned by zml2008** 2023-10-18 14:37 UTC
