### ISSUE TITLE
Incorrect JSONOptions.BY_DATA_VERSION construction or incorrect option defaults

### ISSUE THREAD

**Issue by Spottedleaf** [KyoriPowered/adventure#1015] opened 2023-12-22 10:12 UTC
The option fields default to the modern version (1.20.3+), however the builder does not set `EMIT_HOVER_SHOW_ENTITY_ID_AS_INT_ARRAY` and `VALIDATE_STRICT_EVENTS` for `VERSION_1_16`. 

The default values may be wrong, as the builder for `VERSION_1_20_3` sets the values to their defaults. 
Whichever case it is, the result is that `VERSION_1_16` is emitting compact components, UUIDs as 4 int arrays, and validating strict events.

**Comment by zml2008** [comment] 2023-12-24 01:06
I am unable to reproduce this based on the following test:

```java
  @Test
  void testNonCompactOn116() {
    assertFalse(JSONOptions.byDataVersion().at(2586 /* 1.16.5 data version */).value(JSONOptions.EMIT_HOVER_SHOW_ENTITY_ID_AS_INT_ARRAY));
  }
```

Do you have a test case that can reproduce this issue?

**Comment by zml2008** [comment] 2024-01-27 19:05
Closing due to lack of a response.

**Closed as not planned by zml2008** 2024-01-27 19:05 UTC
