### ISSUE TITLE
UnsupportedOperationException in legacyHoverEventContents

### ISSUE THREAD

**Issue by bundabrg** [KyoriPowered/adventure#237] opened 2020-12-14 09:10 UTC
Using Adventure 4.3.0 compiled into Geyser and connecting a Bedrock player to the map "pixelparty2" running on a vanillacord server behind a Bungeecord server (I know, lots of moving parts) I get the following stacktrace whenever the player attempts to chat:

```
java.lang.UnsupportedOperationException
        at net.kyori.adventure.text.serializer.gson.StyleSerializer.legacyHoverEventContents(StyleSerializer.java:172)
        at net.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:134)
        at net.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:76)
        at net.kyori.adventure.text.serializer.gson.StyleSerializer.deserialize(StyleSerializer.java:51)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.Gson.fromJson(Gson.java:888)
        at com.google.gson.Gson.fromJson(Gson.java:953)
        at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize0(ComponentSerializerImpl.java:158)
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize0(ComponentSerializerImpl.java:111)
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:74)
        at net.kyori.adventure.text.serializer.gson.ComponentSerializerImpl.deserialize(ComponentSerializerImpl.java:55)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.Gson.fromJson(Gson.java:888)
        at com.google.gson.Gson.fromJson(Gson.java:853)
        at com.google.gson.Gson.fromJson(Gson.java:802)
        at com.google.gson.Gson.fromJson(Gson.java:774)
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:83)
        at net.kyori.adventure.text.serializer.gson.GsonComponentSerializerImpl.deserialize(GsonComponentSerializerImpl.java:40)
        at com.github.steveice10.mc.protocol.packet.ingame.server.ServerChatPacket.read(ServerChatPacket.java:51)
        at com.github.steveice10.packetlib.tcp.TcpPacketCodec.decode(TcpPacketCodec.java:59)
        at io.netty.handler.codec.ByteToMessageCodec$1.decode(ByteToMessageCodec.java:42)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:503)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:281)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:326)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:300)
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mdcfe** [comment] 2020-12-14 09:23
What versions of everything aside from Adventure are you using? 

https://github.com/KyoriPowered/adventure/blob/83aa00f10306da10eed73b84caa6255b1e10cfe4/text-serializer-gson/src/main/java/net/kyori/adventure/text/serializer/gson/StyleSerializer.java#L172

Based on this, it looks Geyser is receiving an invalid hover event. I'm not sure there's much that could be done on Adventure's side.

**Comment by MiniDigger** [comment] 2020-12-14 09:35
duplicate of #216, fixed in #217

**Closed by MiniDigger** 2020-12-14 09:35 UTC

**Comment by bundabrg** [comment] 2020-12-14 09:44
Adventure 4.3.0 already contained that commit so I'm not convinced its fixed.

**Comment by MiniDigger** [comment] 2020-12-14 14:35
oh didn't see. I just knew that that exact stack trace was linked in that issue. 

can you provide the json?

**Comment by kashike** [comment] 2020-12-14 17:10
It does not look like Geyser is calling [this method](https://github.com/Steveice10/MCProtocolLib/blob/master/src/main/java/com/github/steveice10/mc/protocol/data/DefaultComponentSerializer.java#L12-L14) to set the serialiser used by the networking library they use, and so no legacy hover event serialiser is used..

**Comment by bundabrg** [comment] 2020-12-15 01:59
Thanks @kashike I also think its not including the relevant library as well so this most likely needs to be fixed there. Thanks for the help @MiniDigger as well.

**Comment by Camotoy** [comment] 2020-12-15 03:30
Addressed in https://github.com/GeyserMC/Geyser/pull/1681. Thanks guys.
